### ISSUE TITLE
Web references are broken

### ISSUE THREAD

**Issue by wvbe** [FontoXML/dita-example-editor#3]
To reproduce:
- Create a web reference
- Click the web reference to invoke the web reference modal

Observed:
- Application crashes

This is caused due to the `:_open-web-reference-modal-for-*` operations not receiving the URL they expect, but a node identifier.

**Comment by brocelot** [comment]
Hi @wvbe 

Thank you for reporting the issue. I expect to take a look at this either this week or the next.

Kind regards,
Michael de Vreugd

**Comment by wvbe** [comment]
Fixed by PR #5 by @harvestcore
